---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PengFuLin.
--- DateTime: 2022/8/3 11:54
function isMyGirl(name)
    return name == 'xiao6' , name
end

local bol,name = isMyGirl('123')

print(name,bol)